import { Job } from "./types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Delivery Executive",
    company: "Zepto Quick Commerce",
    location: "Bandra West, Mumbai",
    salary: { min: 25, max: 32, currency: "/mo" },
    jobType: "Full-time",
    description: "We are looking for experienced delivery executives...",
    requirements: [
      "License and vehicle",
      "Experience in delivery",
      "Good communication",
    ],
    benefits: ["Bonus Included", "Immediate"],
    experienceLevel: "1-2 Years",
    postedAt: "2 hours ago",
    isVerified: true,
    distance: 1.2,
  },
  {
    id: "2",
    title: "Customer Support Associate",
    company: "Swiggy India",
    location: "HSR Layout, Bangalore",
    salary: { min: 18, max: 24, currency: "/mo" },
    jobType: "Full-time",
    description: "Join our customer support team...",
    requirements: ["Good english", "Customer service experience"],
    benefits: ["Remote Available", "Work from office"],
    experienceLevel: "Freshers Welcome",
    postedAt: "5 hours ago",
    isVerified: true,
    distance: 3.8,
    shift: "Night Shift",
  },
  {
    id: "3",
    title: "Warehouse Supervisor",
    company: "Flipkart Logistics",
    location: "Gurugram, Sector 45",
    salary: { min: 40, max: 55, currency: "/mo" },
    jobType: "Full-time",
    description: "Lead a team in our warehouse operations...",
    requirements: ["Warehouse management experience", "Leadership skills"],
    benefits: ["Day Shift", "Incentives"],
    experienceLevel: "3-5 Years",
    postedAt: "1 day ago",
    isVerified: true,
    distance: 8.5,
  },
  {
    id: "4",
    title: "Sales Associate (Retail)",
    company: "Urban Styles Fashion",
    location: "Bandra West, Mumbai",
    salary: { min: 15, max: 20, currency: "/mo" },
    jobType: "Part-time",
    description: "Join our retail team...",
    requirements: ["Sales experience", "Fluent English"],
    benefits: ["Female Only", "Sales Commission"],
    experienceLevel: "0-1 Year",
    postedAt: "4 hours ago",
    isVerified: true,
    distance: 5.2,
  },
];
